//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Project_Team = new HashSet<Project_Team>();
            this.Project_Manager = new HashSet<Project_Manager>();
        }
    
        public string Project_ID { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Description { get; set; }
        public string Document { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Project_Team> Project_Team { get; set; }
        public virtual ICollection<Project_Manager> Project_Manager { get; set; }
    }
}
