//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Managers = new HashSet<Manager>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public string Role_ID { get; set; }
        public string Role_Name { get; set; }
        public int Base_Salary { get; set; }
        public string Badge { get; set; }
    
        public virtual ICollection<Manager> Managers { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
