//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Staff_Team = new HashSet<Staff_Team>();
        }
    
        public string Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public System.DateTime DoB { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Pic { get; set; }
        public string CV { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Datehired { get; set; }
        public Nullable<System.DateTime> Dateleft { get; set; }
        public string Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Staff_Team> Staff_Team { get; set; }
    }
}
